spring:
  application:
    name: config_test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiao-li-J/new-repository
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8888
